name: Build tests GoogleTest
on: { workflow_dispatch, push: { paths-ignore: [ '**', '!qa/**', '!.github/workflows/build-test.yml' ] } }
# Configuration
env:
  test_artifact_name: artifact-build-test
jobs:
  build-tests-gtest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3          
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build tests
        run: |
          MSBuild qa/UnitTest/UnitTest.sln -noLogo -verbosity:minimal -m -p:Platform=x86 -p:Configuration=Debug
          MSBuild qa/UnitTest/UnitTest.sln -noLogo -verbosity:minimal -m -p:Platform=x86 -p:Configuration=Release
          MSBuild qa/UnitTest/UnitTest.sln -noLogo -verbosity:minimal -m -p:Platform=x64 -p:Configuration=Debug
          MSBuild qa/UnitTest/UnitTest.sln -noLogo -verbosity:minimal -m -p:Platform=x64 -p:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.test_artifact_name }}
          path: | # *.pdb for code coverage
            ${{ github.workspace }}/qa/UnitTest/bin/**/*.exe
            ${{ github.workspace }}/qa/UnitTest/bin/**/*.pdb
            ${{ github.workspace }}/qa/UnitTest/bin/**/StaticLibrary.pdb
